/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 21-abr-2017 18:48:06 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS global.tbacao CASCADE
;

DROP TABLE IF EXISTS global.tbformulario CASCADE
;

DROP TABLE IF EXISTS global.tbmodulos CASCADE
;

DROP TABLE IF EXISTS global.tbrotina CASCADE
;

DROP TABLE IF EXISTS global.tbusuario CASCADE
;

/* Create Tables */

CREATE TABLE global.tbacao
(
	acacodigo integer NOT NULL,
	acanome varchar(100) NOT NULL,
	acamethodname varchar(15) NULL,    -- Nome base do método a ser acionado pelo controller
	acaprivilegio smallint NULL   DEFAULT 0    -- Indica se ação poderá ser definida em privilégios.
)
;

CREATE TABLE global.tbformulario
(
	rotcodigo integer NOT NULL,
	acacodigo integer NOT NULL,
	modcodigo integer NOT NULL,
	frmnome varchar(100) NOT NULL,    -- Nome do formulário
	frmclassbase varchar(100) NULL,    -- Indica o nome base da classe para o formulário
	frmincludecontroller smallint NULL   DEFAULT 0    -- Indica se inclui controller específico.
)
;

CREATE TABLE global.tbmodulos
(
	modcodigo integer NOT NULL,    -- Código do módulo
	modnome varchar(50) NOT NULL,    -- Nome do módulo
	moddescricao varchar(200) NULL,    -- Descrição detalhada do módulo
	modsigla varchar(8) NULL,    -- Sigla do módulo
	modexibemenu smallint NOT NULL   DEFAULT 1    -- Indica se o módulo será exibido no menu principal da aplicação
)
;

CREATE TABLE global.tbrotina
(
	rotcodigo integer NOT NULL,    -- Código da rotina
	rotnome varchar(100) NOT NULL,    -- Nome da rotina
	rotdescricao text NULL,    -- Descrição detalhada da rotina
	rotativo smallint NULL   DEFAULT 1,    -- Indica se a rotina está ativa ou não (0 - não, 1 - Sim).
	modcodigo integer NOT NULL
)
;

CREATE TABLE global.tbusuario
(
	usucodigo integer NOT NULL,    -- Código do usuário
	usunome varchar(100) NOT NULL,
	usulogin varchar(20) NOT NULL,    -- Nome de login do usuário (utilizado para login)
	ususenha varchar(40) NULL    -- Senha do usuário formato MD5
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE global.tbacao ADD CONSTRAINT PK_tbacao
	PRIMARY KEY (acacodigo)
;

ALTER TABLE global.tbformulario ADD CONSTRAINT PK_tbformulario
	PRIMARY KEY (rotcodigo,acacodigo)
;

ALTER TABLE global.tbmodulos ADD CONSTRAINT PK_tbmodulos
	PRIMARY KEY (modcodigo)
;

ALTER TABLE global.tbrotina ADD CONSTRAINT PK_tbrotina
	PRIMARY KEY (rotcodigo)
;

ALTER TABLE global.tbusuario ADD CONSTRAINT PK_tbusuario
	PRIMARY KEY (usucodigo)
;

/* Create Foreign Key Constraints */

ALTER TABLE global.tbformulario ADD CONSTRAINT FK_tbformulario_tbacao
	FOREIGN KEY (acacodigo) REFERENCES global.tbacao (acacodigo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE global.tbformulario ADD CONSTRAINT FK_tbformulario_tbmodulos
	FOREIGN KEY (modcodigo) REFERENCES global.tbmodulos (modcodigo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE global.tbformulario ADD CONSTRAINT FK_tbformulario_tbrotina
	FOREIGN KEY (rotcodigo) REFERENCES global.tbrotina (rotcodigo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE global.tbrotina ADD CONSTRAINT FK_tbrotina_tbmodulos
	FOREIGN KEY (modcodigo) REFERENCES global.tbmodulos (modcodigo) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN global.tbacao.acamethodname
	IS 'Nome base do método a ser acionado pelo controller'
;

COMMENT ON COLUMN global.tbacao.acaprivilegio
	IS 'Indica se ação poderá ser definida em privilégios.'
;

COMMENT ON COLUMN global.tbformulario.frmnome
	IS 'Nome do formulário'
;

COMMENT ON COLUMN global.tbformulario.frmclassbase
	IS 'Indica o nome base da classe para o formulário'
;

COMMENT ON COLUMN global.tbformulario.frmincludecontroller
	IS 'Indica se inclui controller específico.'
;

COMMENT ON COLUMN global.tbmodulos.modcodigo
	IS 'Código do módulo'
;

COMMENT ON COLUMN global.tbmodulos.modnome
	IS 'Nome do módulo'
;

COMMENT ON COLUMN global.tbmodulos.moddescricao
	IS 'Descrição detalhada do módulo'
;

COMMENT ON COLUMN global.tbmodulos.modsigla
	IS 'Sigla do módulo'
;

COMMENT ON COLUMN global.tbmodulos.modexibemenu
	IS 'Indica se o módulo será exibido no menu principal da aplicação'
;

COMMENT ON COLUMN global.tbrotina.rotcodigo
	IS 'Código da rotina'
;

COMMENT ON COLUMN global.tbrotina.rotnome
	IS 'Nome da rotina'
;

COMMENT ON COLUMN global.tbrotina.rotdescricao
	IS 'Descrição detalhada da rotina'
;

COMMENT ON COLUMN global.tbrotina.rotativo
	IS 'Indica se a rotina está ativa ou não (0 - não, 1 - Sim).'
;

COMMENT ON COLUMN global.tbusuario.usucodigo
	IS 'Código do usuário'
;

COMMENT ON COLUMN global.tbusuario.usulogin
	IS 'Nome de login do usuário (utilizado para login)'
;

COMMENT ON COLUMN global.tbusuario.ususenha
	IS 'Senha do usuário formato MD5'
;
