/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 21-abr-2017 18:48:37 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS tbenderecopessoa CASCADE
;

DROP TABLE IF EXISTS tbpessoa CASCADE
;

/* Create Tables */

CREATE TABLE tbenderecopessoa
(
	pescodigo integer NOT NULL,
	telcodigo smallint NULL
)
;

CREATE TABLE tbpessoa
(
	pescodigo integer NOT NULL,
	pesnome varchar(150) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE tbenderecopessoa ADD CONSTRAINT PK_tbenderecopessoa
	PRIMARY KEY (pescodigo)
;

CREATE INDEX IXFK_tbenderecopessoa_tbpessoa ON tbenderecopessoa (pescodigo ASC)
;

ALTER TABLE tbpessoa ADD CONSTRAINT PK_tbpessoa
	PRIMARY KEY (pescodigo)
;

/* Create Foreign Key Constraints */

ALTER TABLE tbenderecopessoa ADD CONSTRAINT FK_tbenderecopessoa_tbpessoa
	FOREIGN KEY (pescodigo) REFERENCES tbpessoa (pescodigo) ON DELETE No Action ON UPDATE No Action
;
