<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-03 at 23:26:36.
 */
class est_class_controller_genericTest extends PHPUnit_Framework_TestCase {

    /**
     * @var est_class_controller_generic
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new est_class_controller_generic('unico', 'uni');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers est_class_controller_generic::execute
     * @todo   Implement testExecute().
     */
    public function testExecute() {
        // Remove the following lines when you implement this test.
        $this->assertTrue(true);
    }

    /**
     * @covers est_class_controller_generic::con
     * @todo   Implement testCon().
     */
    public function testCon() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers est_class_controller_generic::inc
     * @todo   Implement testInc().
     */
    public function testInc() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers est_class_controller_generic::alt
     * @todo   Implement testAlt().
     */
    public function testAlt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers est_class_controller_generic::exc
     * @todo   Implement testExc().
     */
    public function testExc() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers est_class_controller_generic::grava
     * @todo   Implement testGrava().
     */
    public function testGrava() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
