<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-10 at 20:41:55.
 */
class est_class_doctrine_initTest extends PHPUnit_Framework_TestCase {

    /**
     * @var est_class_doctrine_init
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new est_class_doctrine_init;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers est_class_doctrine_init::getEntityManagerInstance
     * @todo   Implement testGetEntityManagerInstance().
     */
    public function testGetEntityManagerInstance() {
        $object = Doctrine::getEntityManagerInstance();
        $this->assertFalse($object instanceof est_class_doctrine_init);
    }

}
