/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 21-abr-2017 18:34:14 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS global.tbrotina CASCADE
;

/* Create Tables */

CREATE TABLE global.tbrotina
(
	rotcodigo integer NOT NULL,    -- Código da rotina
	rotnome varchar(100) NOT NULL,    -- Nome da rotina
	rotdescricao text NULL,    -- Descrição detalhada da rotina
	rotativo smallint NULL   DEFAULT 1,    -- Indica se a rotina está ativa ou não (0 - não, 1 - Sim).
	modcodigo integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE global.tbrotina ADD CONSTRAINT PK_tbrotina
	PRIMARY KEY (rotcodigo)
;

/* Create Foreign Key Constraints */

ALTER TABLE global.tbrotina ADD CONSTRAINT FK_tbrotina_tbmodulos
	FOREIGN KEY (modcodigo) REFERENCES global.tbmodulos (modcodigo) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN global.tbrotina.rotcodigo
	IS 'Código da rotina'
;

COMMENT ON COLUMN global.tbrotina.rotnome
	IS 'Nome da rotina'
;

COMMENT ON COLUMN global.tbrotina.rotdescricao
	IS 'Descrição detalhada da rotina'
;

COMMENT ON COLUMN global.tbrotina.rotativo
	IS 'Indica se a rotina está ativa ou não (0 - não, 1 - Sim).'
;